In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])

> Multi Indexing

In [11]:
a[0], a[2], a[-1]

(1, 3, 4)

In [12]:
a [[0,2,-1]]

array([1, 3, 4])

> ### **_Array Types_**

In [15]:
b = np.array([0, .5, 1.2, 1.5])

In [14]:
a.dtype

dtype('int32')

In [16]:
b.dtype

dtype('float64')

In [18]:
# CHANGING DATATYPE OF ARRAY

np.array([1,2,3,4], dtype=float)

array([1., 2., 3., 4.])

In [20]:
np.array([1.2, 2.5 ,3.8, 4.2], dtype=int)

array([1, 2, 3, 4])

In [21]:
c = np.array(['a', 'b', 'c'])

c.dtype

dtype('<U1')

##### 

> ###  **_Dimensions & Shapes_**

In [22]:
A = np.array([
    [1,2,3],
    [4,5,6]
])                   # 2D Array .... Matrix

In [23]:
A.shape

(2, 3)

In [24]:
A.ndim           # Dimensions

2

In [25]:
A.size

6

In [32]:
B = np.array([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [11,12,13],
        [14,15,16],
    ]
])                    # 3D Array.... CUBE

In [33]:
B.shape

(2, 2, 3)

In [34]:
B.ndim

3

In [35]:
B.size

12

If the shape isn't consistent, it'll just fall back to regular python object:

In [36]:
C = np.array([
    [
        [1,2,3]
    ],
    [
        [2,4,6],
        [7,6,5]
    ]
])

C:\Users\Himz\AppData\Local\Temp\ipykernel_6636\1632201935.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  C = np.array([


In [37]:
C.dtype

dtype('O')

In [38]:
C.shape

(2,)

In [39]:
C.size

2

In [40]:
type(C[0])

list

##### 

> ### Indexing & Slicing of Matrices

In [41]:
A = np.array([
    [1,2,3], #0
    [4,5,6], #1
    [7,8,9]  #2
])

In [42]:
A[1]

array([4, 5, 6])

In [43]:
A[1][1]

5

In [47]:
A[1,0]

4

In [48]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
A[:,:2]               # All rows but column upto 2

array([[1, 2],
       [4, 5],
       [7, 8]])

In [52]:
A[:2, :2]            # Rows and columns upto 2

array([[1, 2],
       [4, 5]])

In [53]:
A[:2, 2:]            # Upto 2 rows and from second column

array([[3],
       [6]])

In [54]:
# MODIFICATION

A[1] = np.array([10,10,10])     # Way1

In [55]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [58]:
A[2] = 99                      # Way 2

In [57]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

##### 

> ### Summary Statistics

In [59]:
a

array([1, 2, 3, 4])

In [60]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

In [61]:
a.sum()

10

In [62]:
A.sum()

333

In [63]:
a.mean()

2.5

In [64]:
A.mean()

37.0

In [65]:
A.std()

43.96463225012679

In [66]:
a.std()

1.118033988749895

In [67]:
a.var()

1.25

In [68]:
A.var()

1932.888888888889

In [69]:
A.sum(axis=0)

array([110, 111, 112])

In [72]:
A.sum(axis=1)

array([  6,  30, 297])

In [73]:
A.mean(axis=0)

array([36.66666667, 37.        , 37.33333333])

In [74]:
A.mean(axis=1)

array([ 2., 10., 99.])