In [1]:
import numpy as np

## Linear Algebra

In [3]:
A = np.arange(9).reshape((3,3))

In [4]:
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
B = np.arange(6).reshape((3,2))

In [8]:
B

array([[0, 1],
       [2, 3],
       [4, 5]])

In [9]:
A.dot(B)         # Dot Product

array([[10, 13],
       [28, 40],
       [46, 67]])

In [10]:
A @ B            # Cross Product

array([[10, 13],
       [28, 40],
       [46, 67]])

In [11]:
B.T              # Transposing Matrix (Row -> Column)

array([[0, 2, 4],
       [1, 3, 5]])

In [12]:
B.T @ A

array([[30, 36, 42],
       [39, 48, 57]])

##### 

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Useful Numpy Function

> ### **_random_** 

In [18]:
np.random.random(size=2)

array([0.25988817, 0.19849292])

In [19]:
np.random.normal(size=2)

array([-0.46907238,  0.62413237])

In [20]:
np.random.rand(2,4)

array([[0.45402614, 0.69095757, 0.71514577, 0.89615972],
       [0.36441475, 0.46337186, 0.57531158, 0.25091987]])

----------------------------------------------------------------------------------------------------------------------

> ### **_arange_** 

In [21]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [23]:
np.arange(0, 1, .1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

-------------------------------------------------------------------------------------------------------------

> ### **_reshape_** 

In [24]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [25]:
np.arange(10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

----------------------------------------------------------------------------------------------------

> ### **_linspace_** 

In [26]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [27]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [30]:
np.linspace(0, 1, 2, False)

array([0. , 0.5])

------------

> ### **_zeros, ones, empty_** 

In [31]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [32]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [34]:
np.zeros((3,3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [35]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [36]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [37]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [38]:
np.empty((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

---------

> ### **_identity and eye_** 

In [39]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [40]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [41]:
np.eye(8,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [42]:
np.eye(8, 4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [43]:
np.eye(8, 4, k=-3)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Logic Functions

> #### any()

In [15]:
# Returns True if ANY element in array is zero.

a = np.array([1,2,3,4,5,6,0])
a.any()

True

> #### all()

In [17]:
# Returns True if there is NO zero. All none zero.

a = np.array([1,2,3,4,5,6])
a.all()

True