In [1]:
import numpy as np

## Linear Algebra

In [2]:
A = np.arange(9).reshape((3,3))

In [3]:
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
B = np.arange(6).reshape((3,2))

In [5]:
B

array([[0, 1],
       [2, 3],
       [4, 5]])

In [6]:
A.dot(B)         # Dot Product

array([[10, 13],
       [28, 40],
       [46, 67]])

In [7]:
A @ B            # Cross Product - Matrix Multiplication

array([[10, 13],
       [28, 40],
       [46, 67]])

In [8]:
B.T              # Transposing Matrix (Row -> Column)

array([[0, 2, 4],
       [1, 3, 5]])

In [9]:
B.T @ A

array([[30, 36, 42],
       [39, 48, 57]])

In [10]:
a = np.ones((2,3))
b = np.full((3,2), 2)

np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

##### 

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Useful Numpy Function

> ### **_random_** 

In [11]:
np.random.random(size=2)

array([0.37922383, 0.16734629])

In [12]:
np.random.normal(size=2)

array([-0.14534324, -0.65932349])

In [13]:
np.random.randn(2,4)                # RandN generates data where mean is 0 and Std.Dev as 1

array([[-1.16460963, -0.36987958, -0.03455821,  2.05693292],
       [ 0.24127931,  1.14429007,  0.75305925,  2.37779008]])

In [14]:
a = np.random.rand(2,4)

a

array([[0.98005331, 0.210975  , 0.85766711, 0.01739024],
       [0.17566534, 0.4178157 , 0.5930578 , 0.14090783]])

In [15]:
np.random.random_sample(a.shape)

array([[0.77330754, 0.05329452, 0.06679266, 0.10127794],
       [0.94608694, 0.282169  , 0.35840809, 0.63527744]])

In [16]:
np.random.randint(10, size=(3,3))

array([[2, 7, 0],
       [9, 7, 7],
       [4, 9, 0]])

----------------------------------------------------------------------------------------------------------------------

> ### **_arange_** 

In [17]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [19]:
np.arange(2.3, 5, .3)            # Here upper bound seems including but it's not

array([2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 5. ])

-------------------------------------------------------------------------------------------------------------

> ### vtsack

In [20]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

----------------------------------------------------------------------------------------------------------------------

> ### hstack

In [21]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.hstack([v1,v2])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [22]:
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack([h1,h2])

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

----------------------------------------------------------------------------------------------------------------------

> ### **_reshape_** 

In [23]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [64]:
a = np.arange(10).reshape(5,2)
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [65]:
a.reshape(2,-1)                      # By writing right factorial, -1 detects the second number automatically.

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

----------------------------------------------------------------------------------------------------

> ### **_linspace_** 

In [25]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [26]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [27]:
np.linspace(0, 1, 2, False)

array([0. , 0.5])

In [28]:
np.linspace([1,4,2],3,endpoint=False,axis=1)        # 1 to3, 4 to 3 and 2 to 3.... 50 elements in each

array([[1.  , 1.04, 1.08, 1.12, 1.16, 1.2 , 1.24, 1.28, 1.32, 1.36, 1.4 ,
        1.44, 1.48, 1.52, 1.56, 1.6 , 1.64, 1.68, 1.72, 1.76, 1.8 , 1.84,
        1.88, 1.92, 1.96, 2.  , 2.04, 2.08, 2.12, 2.16, 2.2 , 2.24, 2.28,
        2.32, 2.36, 2.4 , 2.44, 2.48, 2.52, 2.56, 2.6 , 2.64, 2.68, 2.72,
        2.76, 2.8 , 2.84, 2.88, 2.92, 2.96],
       [4.  , 3.98, 3.96, 3.94, 3.92, 3.9 , 3.88, 3.86, 3.84, 3.82, 3.8 ,
        3.78, 3.76, 3.74, 3.72, 3.7 , 3.68, 3.66, 3.64, 3.62, 3.6 , 3.58,
        3.56, 3.54, 3.52, 3.5 , 3.48, 3.46, 3.44, 3.42, 3.4 , 3.38, 3.36,
        3.34, 3.32, 3.3 , 3.28, 3.26, 3.24, 3.22, 3.2 , 3.18, 3.16, 3.14,
        3.12, 3.1 , 3.08, 3.06, 3.04, 3.02],
       [2.  , 2.02, 2.04, 2.06, 2.08, 2.1 , 2.12, 2.14, 2.16, 2.18, 2.2 ,
        2.22, 2.24, 2.26, 2.28, 2.3 , 2.32, 2.34, 2.36, 2.38, 2.4 , 2.42,
        2.44, 2.46, 2.48, 2.5 , 2.52, 2.54, 2.56, 2.58, 2.6 , 2.62, 2.64,
        2.66, 2.68, 2.7 , 2.72, 2.74, 2.76, 2.78, 2.8 , 2.82, 2.84, 2.86,
        2.88, 2.9 , 2.

------------

> ### **_zeros, ones, empty_** 

In [29]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [30]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [31]:
np.zeros((3,3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [32]:
a = np.array([[1,2,3,4],[4,5,6,5]])

np.zeros_like(a)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [33]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [34]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [35]:
a = np.array([[1,2,3,4],[4,5,6,5]])

np.ones_like(a)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [36]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [37]:
np.empty((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

----------------------------------------------------------------------------------------------------------------------

> ### **_identity and eye_** 

In [38]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [39]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [40]:
np.eye(8,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [41]:
np.eye(8, 4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [42]:
np.eye(8, 4, k=-3)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

-----------------------------------------------

> ### ***full***

In [43]:
a = np.full((2,2), 5)

a

array([[5, 5],
       [5, 5]])

In [44]:
b = np.full((2,2,2), 7)

b

array([[[7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7]]])

In [45]:
np.full((2,2,3), [7,10,1])

array([[[ 7, 10,  1],
        [ 7, 10,  1]],

       [[ 7, 10,  1],
        [ 7, 10,  1]]])

-- -----------------------------

> ### ***full_like***

In [46]:
np.full_like(a, 4)

array([[4, 4],
       [4, 4]])

In [47]:
np.full_like(b, 8)

array([[[8, 8],
        [8, 8]],

       [[8, 8],
        [8, 8]]])

----------------------------------------------------------------------------------------------------------------------

> ### ***repeat***

In [48]:
arr = np.array([[1,2,3]])
r = np.repeat(arr, 3, axis=0)

r

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

----------------------------------------------------------------------------------------------------------------------

> ### ***copy***

In [49]:
a = np.array([1,2,3,4])
b = a
b[0] = 10
a

array([10,  2,  3,  4])

In [50]:
a = np.array([1,2,3,4])
b = a.copy()
b[0] = 10
a

array([1, 2, 3, 4])

----------------------------------------------------------------------------------------------------------------------

> ### ***fromfunction()***

In [51]:
np.fromfunction(lambda i,j : i==j, (4,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [52]:
np.fromfunction(lambda i,j : i*j, (4,4))

array([[0., 0., 0., 0.],
       [0., 1., 2., 3.],
       [0., 2., 4., 6.],
       [0., 3., 6., 9.]])

----------------------------------------------------------------------------------------------------------------------

> ### ***fromiter()***

In [53]:
gen = (i*2 for i in range(6))              # Generator function

In [54]:
np.fromiter(gen, dtype=int)

array([ 0,  2,  4,  6,  8, 10])

In [55]:
np.fromiter(range(5), dtype=int)            # range is a function too

array([0, 1, 2, 3, 4])

----------------------------------------------------------------------------------------------------------------------

> ### ***fromstring()***

In [56]:
np.fromstring('1,4,5,7,8,6,4', sep=',')

array([1., 4., 5., 7., 8., 6., 4.])

In [57]:
np.fromstring('12 34 56 43 22 79', sep=' ', dtype= complex)

array([12.+0.j, 34.+0.j, 56.+0.j, 43.+0.j, 22.+0.j, 79.+0.j])

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Logic Functions

> #### any()

In [58]:
# Returns True if ANY element in array is zero.

a = np.array([1,2,3,4,5,6,0])
a.any()

True

> #### all()

In [59]:
# Returns True if there is NO zero. All none zero.

a = np.array([1,2,3,4,5,6])
a.all()

True

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

##### 

## Mathematics

***Check Out For List of Math Func.*** ->  https://numpy.org/doc/stable/reference/routines.math.html

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

##### 

## Miscellaneous

> ### Load Data From File

In [60]:
file = np.genfromtxt('data/untitled.txt', delimiter=',')

file

array([[ 23.,  43.,   6.,   4.,   3.,   2., 532.,  34.,   6.,  23.,  23.,
         12.],
       [ 65.,  76.,   7.,  54.,  34.,  21., 123.,  35.,   7.,   8.,  63.,
         23.],
       [987.,   8., 754.,  43.,  32.,  21.,  23.,  65.,   7.,  98.,   9.,
         90.]])

In [61]:
file = file.astype('int32')

In [62]:
file[file >50]                 # Works just like pandas

array([532,  65,  76,  54, 123,  63, 987, 754,  65,  98,  90])

In [63]:
file[(file>50) & (file<100)]

array([65, 76, 54, 63, 65, 98, 90])